version: '2'

networks:
  front:
    external:
      name: front

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root

  wp:
    depends_on:
      - db
    build: .
    volumes:
      - ./doofinder-for-wordpress:/usr/src/doofinder-for-wordpress
    restart: unless-stopped
    networks:
      default:
      front:
        aliases:
          - wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: root
      DOCKER_SERVICE_PORT: ${DOCKER_SERVICE_PORT}
    ports:
      - "${DOCKER_SERVICE_PORT}:80"
